# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90a7136216eabcc93554857392a42e8bcb486a71e4e184b5b7feb6b7b42ca26f5671a0678cb4915589f736bdaf0345984f22c95a6eb19faa4f3bd03e8353694f

test:
  secret_key_base: 6506de64a2f4d18c9b5f6f9e79ebbd03c5aeb5b7bee8c957290b86670df18e41711fc1d01c979bb52d79e02923e063f947fb4b7f83eace573086820df0ec7797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
